versions:
  # master:
  # #   linux: x64Linux3gcc4.8.2
  #   linux: x64Linux4gcc7.3.0
  # develop:
  # #   linux: x64Linux3gcc4.8.2
  #   linux: x64Linux4gcc7.3.0
  release/7.3.0:
  #   linux: x64Linux3gcc4.8.2
    linux: x64Linux4gcc7.3.0
  release/6.1.2:
  #   linux: x64Linux2.6gcc4.4.5
    linux: x64Linux4gcc7.3.0
